import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './ui/Navbar'
import SideCard from './ui/side-cards'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-body'>
      <body>
        <Navbar/>
        <div className='pl-3 pr-3'>
        <SideCard/>
        </div>
        </body>
    </html>
  )
}
